// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl8TP9rihdHmqNCH7ituV2sp9osavndpM',
    appId: '1:282060800502:web:1f3ebae90369c5a6afc7d7',
    messagingSenderId: '282060800502',
    projectId: 'job-finder-7111c',
    authDomain: 'job-finder-7111c.firebaseapp.com',
    storageBucket: 'job-finder-7111c.firebasestorage.app',
    measurementId: 'G-TLGVGLSK1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWvgO0h4Gt4QZF7Y8dsGFCqRzeUzmjC3A',
    appId: '1:282060800502:android:30c5a051dcbf7267afc7d7',
    messagingSenderId: '282060800502',
    projectId: 'job-finder-7111c',
    storageBucket: 'job-finder-7111c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDph5N7wsGyqXofjih7D3Z7GIJsIOo4zOc',
    appId: '1:282060800502:ios:ed7aa05a58ac49d8afc7d7',
    messagingSenderId: '282060800502',
    projectId: 'job-finder-7111c',
    storageBucket: 'job-finder-7111c.firebasestorage.app',
    iosBundleId: 'com.example.jobspot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDph5N7wsGyqXofjih7D3Z7GIJsIOo4zOc',
    appId: '1:282060800502:ios:ed7aa05a58ac49d8afc7d7',
    messagingSenderId: '282060800502',
    projectId: 'job-finder-7111c',
    storageBucket: 'job-finder-7111c.firebasestorage.app',
    iosBundleId: 'com.example.jobspot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl8TP9rihdHmqNCH7ituV2sp9osavndpM',
    appId: '1:282060800502:web:f09b0c51f7ffb487afc7d7',
    messagingSenderId: '282060800502',
    projectId: 'job-finder-7111c',
    authDomain: 'job-finder-7111c.firebaseapp.com',
    storageBucket: 'job-finder-7111c.firebasestorage.app',
    measurementId: 'G-594YLS3320',
  );
}
